---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1sxl6aavsr7h5a3n2q8ke0geeg48xtl0ydq62jr0kdvf7nxh2fdqs6w0rja
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1sxl6aavsr7h5a3n2q8ke0geeg48xtl0ydq62jr0kdvf7nxh2fdqs6w0rja
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1sxl6aavsr7h5a3n2q8ke0geeg48xtl0ydq62jr0kdvf7nxh2fdqs6w0rja
