---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  KUBE_VIP_ADDR: "10.0.100.253"
  METALLB_LB_RANGE: "10.0.100.50-10.0.100.60"
  METALLB_K8S_GATEWAY_ADDR: "10.0.100.50"
  METALLB_INGRESS_ADDR: "10.0.100.51"
